/** Copy for the internal component review page. Not part of the public site. */
export const gallery = {
  title: "component review",
  intro:
    "Every component in every variant, at desktop width and inside a 375px column. Use the state toggle to force hover, focus, disabled and error where they apply.",
  stateLabel: "state:",
  states: {
    rest: "rest",
    hover: "hover",
    focus: "focus",
    disabled: "disabled",
    error: "error",
  },
  desktop: "desktop",
  designKey: "/dev/design",
  mobile: "375px",
  sections: {
    window: "1. RetroWindow",
    dialog: "2. DialogBox",
    frame: "3. DottedFrame",
    folder: "4. FolderTab",
    doc: "5. DocIcon",
    hearts: "6. HeartRow",
    search: "7. SearchBar",
    decor: "8. Decorations",
    button: "9. Button",
    field: "10. Field",
  },
  windowTitle: "untitled",
  windowUrl: "https://example.com/essays",
  lorem:
    "Body text is ink on cream. This paragraph exists to check line length, padding and outline weight against the reference.",
  short: "Card body. Two short lines of ink on cream.",
  dialogPrompt: "do you want to continue?",
  dialogYes: "yes pressed",
  dialogNo: "no pressed",
  folderLabels: ["single", "bundle", "full"],
  docLabel: "sample.doc",
  searchEcho: "value:",
  buttonLabel: "button",
  buttonLink: "link button",
  field: {
    text: "text input",
    email: "email",
    select: "select",
    radio: "radio group",
    textarea: "textarea",
  },
  fieldHelp: "Help text sits under the control in body font.",
  fieldError: "this field has an error",
  fieldPlaceholder: "choose one",
  options: [
    { value: "a", label: "Option a", hint: "A hint line under the option." },
    { value: "b", label: "Option b" },
    { value: "c", label: "Option c" },
  ],
} as const;
